// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

/**
 * Type of command being sent to the arm (Dimensonal units)
 */
public final class EClientCommandMode {
  private EClientCommandMode() { }
  public static final byte NO_COMMAND_MODE = 0;
  public static final byte POSITION = 1;
  public static final byte WRENCH = 2;
  public static final byte TORQUE = 3;

  public static final String[] names = { "NO_COMMAND_MODE", "POSITION", "WRENCH", "TORQUE", };

  public static String name(int e) { return names[e]; }
}

