# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class ArmState(object):
    NONE = 0
    StartArm = 1
    StopArm = 2
    PauseArm = 3
    ShutdownArm = 4
    TeachArm = 5
    MoveArmTrajectory = 6
    MoveArmJointServo = 7
    MoveArmCartesianServo = 8

