// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

public final class DeviceState {
  private DeviceState() { }
  public static final byte NONE = 0;
  public static final byte KUKAiiwaState = 1;
  public static final byte FusionTrackMessage = 2;

  public static final String[] names = { "NONE", "KUKAiiwaState", "FusionTrackMessage", };

  public static String name(int e) { return names[e]; }
}

