# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class Disabled(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDisabled(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Disabled()
        x.Init(buf, n + offset)
        return x

    # Disabled
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DisabledStart(builder): builder.StartObject(0)
def DisabledEnd(builder): return builder.EndObject()
