# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

# /// Type of command being sent to the arm (Dimensonal units)
class EClientCommandMode(object):
    NO_COMMAND_MODE = 0
    POSITION = 1
    WRENCH = 2
    TORQUE = 3

