// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

public final class EConnectionQuality {
  private EConnectionQuality() { }
  public static final byte POOR = 0;
  public static final byte FAIR = 1;
  public static final byte GOOD = 2;
  public static final byte EXCELLENT = 3;

  public static final String[] names = { "POOR", "FAIR", "GOOD", "EXCELLENT", };

  public static String name(int e) { return names[e]; }
}

