// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

public final class EControlMode {
  private EControlMode() { }
  public static final byte POSITION_CONTROL_MODE = 0;
  public static final byte CART_IMP_CONTROL_MODE = 1;
  public static final byte JOINT_IMP_CONTROL_MODE = 2;
  public static final byte NO_CONTROL = 3;

  public static final String[] names = { "POSITION_CONTROL_MODE", "CART_IMP_CONTROL_MODE", "JOINT_IMP_CONTROL_MODE", "NO_CONTROL", };

  public static String name(int e) { return names[e]; }
}

