# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class EControlMode(object):
    POSITION_CONTROL_MODE = 0
    CART_IMP_CONTROL_MODE = 1
    JOINT_IMP_CONTROL_MODE = 2
    NO_CONTROL = 3

