# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class EDriveState(object):
# /// Driving mode currently unused
    OFF = 1
# /// About to drive
    TRANSITIONING = 2
# /// Actively commanding arm
    ACTIVE = 3

