# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class ESafetyState(object):
    NORMAL_OPERATION = 0
    SAFETY_STOP_LEVEL_0 = 1
    SAFETY_STOP_LEVEL_1 = 2
    SAFETY_STOP_LEVEL_2 = 3

