# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class ESessionState(object):
# /// No session
    IDLE = 0
# /// Monitoring mode, receive state but connection too inconsistent to command
    MONITORING_WAIT = 1
# /// Monitoring mode
    MONITORING_READY = 2
# /// About to command (Overlay created in Java interface)
    COMMANDING_WAIT = 3
# /// Actively commanding the arm with FRI
    COMMANDING_ACTIVE = 4

