// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

public final class EulerOrder {
  private EulerOrder() { }
  public static final byte xyz = 0;
  public static final byte yzx = 1;
  public static final byte zxy = 2;
  public static final byte xzy = 3;
  public static final byte zyx = 4;
  public static final byte yxz = 5;
  public static final byte zxz = 6;
  public static final byte xyx = 7;
  public static final byte yzy = 8;
  public static final byte xzx = 9;
  public static final byte yxy = 10;

  public static final String[] names = { "xyz", "yzx", "zxy", "xzy", "zyx", "yxz", "zxz", "xyx", "yzy", "xzx", "yxy", };

  public static String name(int e) { return names[e]; }
}

