# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class EulerXYZd(object):
    __slots__ = ['_tab']

    # EulerXYZd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EulerXYZd
    def Rx(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EulerXYZd
    def Ry(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # EulerXYZd
    def Rz(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateEulerXYZd(builder, rx, ry, rz):
    builder.Prep(8, 24)
    builder.PrependFloat64(rz)
    builder.PrependFloat64(ry)
    builder.PrependFloat64(rx)
    return builder.Offset()
