# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class FRITimeStamp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFRITimeStamp(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FRITimeStamp()
        x.Init(buf, n + offset)
        return x

    # FRITimeStamp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FRITimeStamp
    def Sec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FRITimeStamp
    def Nanosec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FRITimeStampStart(builder): builder.StartObject(2)
def FRITimeStampAddSec(builder, sec): builder.PrependInt32Slot(0, sec, 0)
def FRITimeStampAddNanosec(builder, nanosec): builder.PrependInt32Slot(1, nanosec, 0)
def FRITimeStampEnd(builder): return builder.EndObject()
