// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

public final class ftkDeviceType {
  private ftkDeviceType() { }
  public static final int DEV_SIMULATOR = 0;
  public static final int DEV_INFINITRACK = 1;
  public static final int DEV_FUSIONTRACK_500 = 2;
  public static final int DEV_FUSIONTRACK_250 = 3;
  public static final int DEV_UNKNOWN_DEVICE = 127;
}

