# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class ftkDeviceType(object):
    DEV_SIMULATOR = 0
    DEV_INFINITRACK = 1
    DEV_FUSIONTRACK_500 = 2
    DEV_FUSIONTRACK_250 = 3
    DEV_UNKNOWN_DEVICE = 127

