# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

class ftkQueryStatus(object):
    QS_WAR_SKIPPED = -1
    QS_OK = 0
    QS_ERR_OVERFLOW = 1
    QS_ERR_INVALID_RESERVED_SIZE = 2
    QS_REPROCESS = 10

