// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

public final class ftkQueryStatus {
  private ftkQueryStatus() { }
  public static final int QS_WAR_SKIPPED = -1;
  public static final int QS_OK = 0;
  public static final int QS_ERR_OVERFLOW = 1;
  public static final int QS_ERR_INVALID_RESERVED_SIZE = 2;
  public static final int QS_REPROCESS = 10;

  public static final String[] names = { "QS_WAR_SKIPPED", "QS_OK", "QS_ERR_OVERFLOW", "QS_ERR_INVALID_RESERVED_SIZE", "", "", "", "", "", "", "", "QS_REPROCESS", };

  public static String name(int e) { return names[e - QS_WAR_SKIPPED]; }
}

