# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class FusionTrackMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFusionTrackMessage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FusionTrackMessage()
        x.Init(buf, n + offset)
        return x

    # FusionTrackMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FusionTrackMessage
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # FusionTrackMessage
    def Parameters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .FusionTrackParameters import FusionTrackParameters
            obj = FusionTrackParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FusionTrackMessage
    def TimeEvent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TimeEvent import TimeEvent
            obj = TimeEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FusionTrackMessage
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .FusionTrackFrame import FusionTrackFrame
            obj = FusionTrackFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FusionTrackMessageStart(builder): builder.StartObject(4)
def FusionTrackMessageAddTimestamp(builder, timestamp): builder.PrependFloat64Slot(0, timestamp, 0.0)
def FusionTrackMessageAddParameters(builder, parameters): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(parameters), 0)
def FusionTrackMessageAddTimeEvent(builder, timeEvent): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timeEvent), 0)
def FusionTrackMessageAddFrame(builder, frame): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(frame), 0)
def FusionTrackMessageEnd(builder): return builder.EndObject()
