# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class Inertia(object):
    __slots__ = ['_tab']

    # Inertia
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Inertia
    def Mass(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Inertia
    def Pose(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 8)
        return obj

    # Inertia
    def Ixx(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64))
    # Inertia
    def Ixy(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(72))
    # Inertia
    def Ixz(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(80))
    # Inertia
    def Iyy(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(88))
    # Inertia
    def Iyz(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(96))
    # Inertia
    def Izz(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(104))

def CreateInertia(builder, mass, pose_position_x, pose_position_y, pose_position_z, pose_orientation_x, pose_orientation_y, pose_orientation_z, pose_orientation_w, ixx, ixy, ixz, iyy, iyz, izz):
    builder.Prep(8, 112)
    builder.PrependFloat64(izz)
    builder.PrependFloat64(iyz)
    builder.PrependFloat64(iyy)
    builder.PrependFloat64(ixz)
    builder.PrependFloat64(ixy)
    builder.PrependFloat64(ixx)
    builder.Prep(8, 56)
    builder.Prep(8, 32)
    builder.PrependFloat64(pose_orientation_w)
    builder.PrependFloat64(pose_orientation_z)
    builder.PrependFloat64(pose_orientation_y)
    builder.PrependFloat64(pose_orientation_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(pose_position_z)
    builder.PrependFloat64(pose_position_y)
    builder.PrependFloat64(pose_position_x)
    builder.PrependFloat64(mass)
    return builder.Offset()
