// automatically generated by the FlatBuffers compiler, do not modify

package grl.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class KUKAiiwaFusionTrackMessage extends Table {
  public static KUKAiiwaFusionTrackMessage getRootAsKUKAiiwaFusionTrackMessage(ByteBuffer _bb) { return getRootAsKUKAiiwaFusionTrackMessage(_bb, new KUKAiiwaFusionTrackMessage()); }
  public static KUKAiiwaFusionTrackMessage getRootAsKUKAiiwaFusionTrackMessage(ByteBuffer _bb, KUKAiiwaFusionTrackMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public KUKAiiwaFusionTrackMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double timestamp() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public TimeEvent timeEvent() { return timeEvent(new TimeEvent()); }
  public TimeEvent timeEvent(TimeEvent obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte deviceStateType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table deviceState(Table obj) { int o = __offset(10); return o != 0 ? __union(obj, o) : null; }

  public static int createKUKAiiwaFusionTrackMessage(FlatBufferBuilder builder,
      double timestamp,
      int timeEventOffset,
      byte deviceState_type,
      int deviceStateOffset) {
    builder.startObject(4);
    KUKAiiwaFusionTrackMessage.addTimestamp(builder, timestamp);
    KUKAiiwaFusionTrackMessage.addDeviceState(builder, deviceStateOffset);
    KUKAiiwaFusionTrackMessage.addTimeEvent(builder, timeEventOffset);
    KUKAiiwaFusionTrackMessage.addDeviceStateType(builder, deviceState_type);
    return KUKAiiwaFusionTrackMessage.endKUKAiiwaFusionTrackMessage(builder);
  }

  public static void startKUKAiiwaFusionTrackMessage(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addTimestamp(FlatBufferBuilder builder, double timestamp) { builder.addDouble(0, timestamp, 0.0); }
  public static void addTimeEvent(FlatBufferBuilder builder, int timeEventOffset) { builder.addOffset(1, timeEventOffset, 0); }
  public static void addDeviceStateType(FlatBufferBuilder builder, byte deviceStateType) { builder.addByte(2, deviceStateType, 0); }
  public static void addDeviceState(FlatBufferBuilder builder, int deviceStateOffset) { builder.addOffset(3, deviceStateOffset, 0); }
  public static int endKUKAiiwaFusionTrackMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

