# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class KUKAiiwaState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKUKAiiwaState(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KUKAiiwaState()
        x.Init(buf, n + offset)
        return x

    # KUKAiiwaState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KUKAiiwaState
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # KUKAiiwaState
    def Destination(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # KUKAiiwaState
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # KUKAiiwaState
    def TimeStamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TimeEvent import TimeEvent
            obj = TimeEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KUKAiiwaState
    def SetArmControlState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

    # KUKAiiwaState
    def ArmControlState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .ArmControlState import ArmControlState
            obj = ArmControlState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KUKAiiwaState
    def SetArmConfiguration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

    # KUKAiiwaState
    def ArmConfiguration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .KUKAiiwaArmConfiguration import KUKAiiwaArmConfiguration
            obj = KUKAiiwaArmConfiguration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KUKAiiwaState
    def HasMonitorState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

    # KUKAiiwaState
    def MonitorState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .KUKAiiwaMonitorState import KUKAiiwaMonitorState
            obj = KUKAiiwaMonitorState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KUKAiiwaState
    def HasMonitorConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

    # KUKAiiwaState
    def MonitorConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .KUKAiiwaMonitorConfiguration import KUKAiiwaMonitorConfiguration
            obj = KUKAiiwaMonitorConfiguration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KUKAiiwaState
    def FRIMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .FRIMessageLog import FRIMessageLog
            obj = FRIMessageLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def KUKAiiwaStateStart(builder): builder.StartObject(13)
def KUKAiiwaStateAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def KUKAiiwaStateAddDestination(builder, destination): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(destination), 0)
def KUKAiiwaStateAddSource(builder, source): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)
def KUKAiiwaStateAddTimeStamp(builder, timeStamp): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timeStamp), 0)
def KUKAiiwaStateAddSetArmControlState(builder, setArmControlState): builder.PrependBoolSlot(4, setArmControlState, 0)
def KUKAiiwaStateAddArmControlState(builder, armControlState): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(armControlState), 0)
def KUKAiiwaStateAddSetArmConfiguration(builder, setArmConfiguration): builder.PrependBoolSlot(6, setArmConfiguration, 0)
def KUKAiiwaStateAddArmConfiguration(builder, armConfiguration): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(armConfiguration), 0)
def KUKAiiwaStateAddHasMonitorState(builder, hasMonitorState): builder.PrependBoolSlot(8, hasMonitorState, 0)
def KUKAiiwaStateAddMonitorState(builder, monitorState): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(monitorState), 0)
def KUKAiiwaStateAddHasMonitorConfig(builder, hasMonitorConfig): builder.PrependBoolSlot(10, hasMonitorConfig, 0)
def KUKAiiwaStateAddMonitorConfig(builder, monitorConfig): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(monitorConfig), 0)
def KUKAiiwaStateAddFRIMessage(builder, FRIMessage): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(FRIMessage), 0)
def KUKAiiwaStateEnd(builder): return builder.EndObject()
