# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class KUKAiiwaStates(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsKUKAiiwaStates(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KUKAiiwaStates()
        x.Init(buf, n + offset)
        return x

    # KUKAiiwaStates
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KUKAiiwaStates
    def States(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .KUKAiiwaState import KUKAiiwaState
            obj = KUKAiiwaState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KUKAiiwaStates
    def StatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def KUKAiiwaStatesStart(builder): builder.StartObject(1)
def KUKAiiwaStatesAddStates(builder, states): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(states), 0)
def KUKAiiwaStatesStartStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def KUKAiiwaStatesEnd(builder): return builder.EndObject()
