# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class LinkObject(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLinkObject(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LinkObject()
        x.Init(buf, n + offset)
        return x

    # LinkObject
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LinkObject
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # LinkObject
    def Parent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # LinkObject
    def Pose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .Pose import Pose
            obj = Pose()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LinkObject
    def Inertia(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .Inertia import Inertia
            obj = Inertia()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def LinkObjectStart(builder): builder.StartObject(4)
def LinkObjectAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def LinkObjectAddParent(builder, parent): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(parent), 0)
def LinkObjectAddPose(builder, pose): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pose), 0)
def LinkObjectAddInertia(builder, inertia): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(inertia), 0)
def LinkObjectEnd(builder): return builder.EndObject()
