# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class LogKUKAiiwaFusionTrack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLogKUKAiiwaFusionTrack(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LogKUKAiiwaFusionTrack()
        x.Init(buf, n + offset)
        return x

    # LogKUKAiiwaFusionTrack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LogKUKAiiwaFusionTrack
    def States(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .KUKAiiwaFusionTrackMessage import KUKAiiwaFusionTrackMessage
            obj = KUKAiiwaFusionTrackMessage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LogKUKAiiwaFusionTrack
    def StatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def LogKUKAiiwaFusionTrackStart(builder): builder.StartObject(1)
def LogKUKAiiwaFusionTrackAddStates(builder, states): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(states), 0)
def LogKUKAiiwaFusionTrackStartStatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LogKUKAiiwaFusionTrackEnd(builder): return builder.EndObject()
