# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class MoveArmTrajectory(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMoveArmTrajectory(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MoveArmTrajectory()
        x.Init(buf, n + offset)
        return x

    # MoveArmTrajectory
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MoveArmTrajectory
    def Traj(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .JointState import JointState
            obj = JointState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MoveArmTrajectory
    def TrajLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def MoveArmTrajectoryStart(builder): builder.StartObject(1)
def MoveArmTrajectoryAddTraj(builder, traj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(traj), 0)
def MoveArmTrajectoryStartTrajVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def MoveArmTrajectoryEnd(builder): return builder.EndObject()
