# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class ShutdownArm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsShutdownArm(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShutdownArm()
        x.Init(buf, n + offset)
        return x

    # ShutdownArm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ShutdownArmStart(builder): builder.StartObject(0)
def ShutdownArmEnd(builder): return builder.EndObject()
