# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class StopArm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStopArm(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StopArm()
        x.Init(buf, n + offset)
        return x

    # StopArm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StopArmStart(builder): builder.StartObject(0)
def StopArmEnd(builder): return builder.EndObject()
