# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class VrepPath(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVrepPath(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VrepPath()
        x.Init(buf, n + offset)
        return x

    # VrepPath
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VrepPath
    def ControlPoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .VrepControlPoint import VrepControlPoint
            obj = VrepControlPoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VrepPath
    def ControlPointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def VrepPathStart(builder): builder.StartObject(1)
def VrepPathAddControlPoints(builder, controlPoints): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(controlPoints), 0)
def VrepPathStartControlPointsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VrepPathEnd(builder): return builder.EndObject()
