# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer

import flatbuffers

class Wrench(object):
    __slots__ = ['_tab']

    # Wrench
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Wrench
    def Force(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Wrench
    def Torque(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj

    # Wrench
    def ForceOffset(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 48)
        return obj


def CreateWrench(builder, force_x, force_y, force_z, torque_x, torque_y, torque_z, force_offset_x, force_offset_y, force_offset_z):
    builder.Prep(8, 72)
    builder.Prep(8, 24)
    builder.PrependFloat64(force_offset_z)
    builder.PrependFloat64(force_offset_y)
    builder.PrependFloat64(force_offset_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(torque_z)
    builder.PrependFloat64(torque_y)
    builder.PrependFloat64(torque_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(force_z)
    builder.PrependFloat64(force_y)
    builder.PrependFloat64(force_x)
    return builder.Offset()
